<?php
$titre 			= "Contact : Partagez vos connaissances sur le saumon";
$keywords 		= "education, connaissances, partage, saumon, omega-3, informations, idees, recettes, culture, commentaires, commentaire, remarques, cholesterol, suggestions, salmonide";
$description	= "Questions, suggestions, écrivez-nous et partagez votre avis sur le saumon, ses bienfaits. Faites découvrir vos recettes et expériences cullinaires";
?>
