<?php
$titre 			= "Recettes : Saumon fumé, tartare et autres";
$keywords		= "cuisine, repas, poisson atlantique, pacifique, gravlax, produits de la mer, keta, rouge, rose, ouananiche, wananish, omega-3, caviar, poisson d'elevage";
$description	= "Consultez nos recettes à base de saumon. Savourez nos plats de tartares, de gravlax avec ou sans sauce. Découvrez nos repas du Chili, du Japon et de la Scandinavie";
?>