<?php
$titre 			= "Informations : Avantages et bénéfices des OMEGA-3";
$keywords 		= "poisson, saumon, cholesterol, medicaliment, neutraceutique, alicament, maladies cardiaques, mémoire, stress, omega3, equilibre emotionnel, omega-6, omega-9";
$description 	= "Découvrez les avantages de la consommation de saumon, les effets sur le système immunitaire, la réduction du cholestérol et du stress, l'amélioration de la mémoire, réduisez vos risques d'ACV";
?>