<?php
include("recettes/recettes_manager.php.inc");

$titre 			= "Recettes : Saumon fumé, tartare et autres";
$keywords		= "cuisine, repas, poisson atlantique, pacifique, gravlax, produits de la mer, keta, rouge, rose, ouananiche, wananish, omega-3, caviar, poisson d'elevage";
$description	= "Consultez nos recettes à base de saumon. Savourez nos plats de tartares, de gravlax avec ou sans sauce. Découvrez nos repas du Chili, du Japon et de la Scandinavie";


echo '  <!-- Style de lazyloading -->
		<link rel="stylesheet" type="text/css" href="assets/css/lazyloading/component.css" />
		<link rel="stylesheet" type="text/css" href="assets/css/lazyloading/default.css" />
		<!-- Script de lazyloading -->
		<script type="text/javascript" src="assets/js/lazyloading/modernizr.custom.js"></script>
		<script type="text/javascript" src="assets/js/lazyloading/masonry.pkgd.min.js"></script>
		<script type="text/javascript" src="assets/js/lazyloading/imagesloaded.js"></script>
		<script type="text/javascript" src="assets/js/lazyloading/classie.js"></script>
		<script type="text/javascript" src="assets/js/lazyloading/AnimOnScroll.js"></script>';
?>