-- phpMyAdmin SQL Dump
-- version 4.0.4
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Jeu 26 Septembre 2013 à 13:41
-- Version du serveur: 5.5.24-log
-- Version de PHP: 5.3.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `isaumon`
--

-- --------------------------------------------------------

--
-- Structure de la table `recettes`
--

CREATE TABLE IF NOT EXISTS `recettes` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `titre` varchar(555) COLLATE utf8_bin NOT NULL,
  `commentaire` varchar(555) COLLATE utf8_bin NOT NULL,
  `ingredients` text COLLATE utf8_bin NOT NULL,
  `portion` int(4) NOT NULL,
  `tpspreparation` int(4) DEFAULT NULL COMMENT 'temps de preparation',
  `tpscuisson` int(4) DEFAULT NULL COMMENT 'temps de cuisson',
  `mdcuisson` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT 'mode cuissom',
  `preparation` text COLLATE utf8_bin,
  `evaluation` float DEFAULT NULL,
  `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `img` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=35 ;

--
-- Contenu de la table `recettes`
--

INSERT INTO `recettes` (`id`, `titre`, `commentaire`, `ingredients`, `portion`, `tpspreparation`, `tpscuisson`, `mdcuisson`, `preparation`, `evaluation`, `date`, `img`) VALUES
(1, 'Mousse d''asperge au saumon fumé', 'Une verrine très fraîche au goût subtil d''asperge et de saumon fumé, un duo gagnant !', '300 g d''asperges blanches en conserve (garder 5 cl de jus pour la recette);\r\n2 oeufs durs;\r\n5 cuillères à soupe de crème allégée à 15 %;\r\n4 tranches de saumon fumé;\r\n3 feuilles de gélatine (3 g);', 4, NULL, 120, NULL, 'Faites tremper les feuilles de gélatine dans un bol d''eau froide.\r\nPortez à ébullition 5 cl du jus des asperges. Essorez la gélatine entre vos mains et faites-la dissoudre dans le jus chauffé, hors du feu. Laissez refroidir.\r\n\r\nMixez ensemble les asperges coupées en tronçons, les œufs écalés et coupés en morceaux, la crème fraîche et le jus d''asperge contenant la gélatine. Vous devez obtenir une crème bien lisse. Versez dans des mini verrines en les remplissant aux deux tiers. Placez au réfrigérateur au moins 3 heures.\r\n\r\nCoupez le saumon fumé en petits dés et répartissez-les sur la mousse d''asperge dans les verrines. Décorez avec un brin d''aneth ou autre aromatique à votre goût.\r\n\r\nServez frais en entrée ou lors de vos apéritifs dînatoires.', 9, '2013-09-16 04:00:00', ''),
(18, 'Quiche Saumon-fromage de ch', 'Quiche Saumon-fromage de ch', '200 g de de saumon sans peau, 15 0 g de fromage de ch', 5, 15, 35, 'Four', '', 8, '2013-09-25 15:38:51', 'saumon_fromage.jpg'),
(19, 'Bagles au saumon fum', 'Bagles au saumon fum', '15 tranches de saumon fum', 1, 5, 0, 'Four', 'Couper les bagels en deux et les faire toaster l', 8, '2013-09-25 15:41:52', 'Bagles_au_saumon.jpg'),
(20, 'Terrine de saumon', 'Terrine de saumon', '', 10, 10, 15, 'Four', '', 8, '2013-09-25 16:52:58', 'Terrine_de_saumon.jpg'),
(21, 'Terrine de saumon', 'Terrine de saumon', '- 30 cl de vin blanc\r\n- 30 cl d''eau\r\n- 30 jus de citron\r\n- 40 g dâ€™Ã©chalotes hachÃ©es\r\n- 1 cuillÃ¨re Ã  cafÃ© d''estragon hachÃ©\r\n-  sel et poivre au goÃ»t\r\n', 2, 5, 10, 'Four', 'Garder verres dans le rÃ©frigÃ©rateur.\r\nPrÃ©parer des laniÃ¨res de saumon de 1 Ã  deux cm. Couper le poivrons en dÃ©s et mÃ©langer avec le saumon et les ingrÃ©dients de la marinade.\r\nFaire cuire lâ€™Å“uf pendant 10 minutes, puis les rafraÃ®chir Ã  lâ€™aide de lâ€™eau froide. SÃ©parer les jaunes des blancs ; garder les blancs et les hacher.\r\nPrÃ©parer la gelÃ©e instantanÃ©e puis la mettre au rÃ©frigÃ©rateur. Remuer chaque 5 minutes afin qu''elle ne fige pas et qu''elle prenne la consistante de l''huile.\r\nEnlever la pelure des citrons puis dÃ©tacher les tranches et enlever le plus possible la membrane. DÃ©couper en trois les tranches.\r\nÃ‰goutter le saumon de la marinade. Faire le saumon aux micro-ondes pendant 3 minutes Ã  puissance maximale.\r\nMÃ©langer 100 ml de gelÃ©e avec les blancs d''Å“ufs hachÃ©s, les dÃ©s de citron, les poivrons, le poivre vert, le persil, le cerfeuil et l''estragon.\r\nRecouvrir le fond des verres avec 2 cm de gelÃ©e, mettre Ã  gÃ©lifier au rÃ©frigÃ©rateur, ajouter une couche de laniÃ¨res de saumon, repartir la moitiÃ© de la gelÃ©e du mÃ©lange dans les verres remettre au rÃ©frigÃ©rateur ; recommencer cette opÃ©ration une seconde fois, puis finir de remplir le moule avec la gelÃ©e restante; conservez dans le rÃ©frigÃ©rateur pendant 24 heures. Servir accompagnÃ© d''une mayonnaise.\r\n', 5, '2013-09-25 17:00:01', 'Terrine_de_saumon.jpg'),
(28, 'Tarte au saumon et patate', 'Une tarte parfaite pour le souper ou dÃ©jeuner au patate et au saumon. Un vrai dÃ©lice qui plait au fan de saumon.', '2 grosses pomme de terre \r\nun paquet de saumon fumÃ© \r\nune patte feuilletÃ©e \r\n3 oeufs \r\n5 brins d''aneth ( ou plus selon vos gouts)\r\n6 c a s de crÃ©mÃ© fraiche entiÃ¨re\r\n2 poignÃ©es de gruyÃ¨re rappÃ© poivre', 8, 15, 30, 'Four', 'PrÃ©chauffer le four Ã  200Â°.\r\nPelucher les pommes de terre, les couper en dÃ¨s et les cuire dans de l eau salÃ©.\r\nSurveiller la cuisson. Gouter les et les laisser tiÃ©dir.\r\nDans un rÃ©cipient, battre les 3 oeufs avec les 6 c a soupe de crÃ¨me,\r\nl''aneth hachÃ©e, ajouter le gruyÃ¨re et poivrer.\r\nÃ‰taler la patte feuilletÃ©e sur un plateau Ã  tarte,\r\nmettre les pommes de terre au fond puis ajouter le saumon fumÃ© coupÃ© en morceau et\r\nverser la prÃ©paration aux oeufs.\r\nMettre au four Ã  200Â° et cuire environ 25 Ã  30 minutes.\r\nRapide et dÃ©licieux avec une petite salade ou pour accompagner une viande grillÃ©e.', 9, '2013-09-26 13:02:21', 'Tarte_au_saumon_et_patate.jpg'),
(29, 'Saumon au whisky', 'Une assiette au saumon marinÃ©e au whisky avec un soupons de coriandre fraÃ®che.\r\nCette combinaison de saveurs va forcement activer vos papilles gustative. Un repas trÃ¨s simple. PrÃ©parer la marinade 24hrs d''avance.', '1 filet de saumon de 225 g (1/2 livre) avec la peau, trÃ¨s frais\r\n30 ml ( 2 c. Ã  soupe) de whisky\r\nsel de mer\r\nsucre\r\npoivre frais moulu\r\n60 ml (1/4 tasse) environ d''herbes fraÃ®ches ( mÃ©lisse, coriandre ou aneth)', 4, 20, 12, 'Four', '- DÃ©poser le filet de saumon, cÃ´tÃ© peau dans l''assiette.\r\n- Arroser de whisky.\r\n- Saler le saumon un peu plus qu''Ã  la normale.\r\n- Saupoudrer la mÃªme quantitÃ© de sucre.\r\n- Poivrer et rÃ©partir les herbes sur le poisson.\r\n- Presser les herbes et retourner le poisson.\r\n- Couvrir d''une pellicule de plastique. Laisser mariner 24 heures au rÃ©frigÃ©rateur.', 8, '2013-09-26 13:18:17', 'recette_saumon_whisky.jpg'),
(30, 'Saumon grillÃ©s au piment chili, aux poivrons et aux courgettes', 'Un mÃ©lange onctueux de lÃ©gumes frais servie Ã  cÃ´tÃ© d''un filet de saumon grillÃ© Ã  la perfection.', '2 c. Ã  tab (30 ml) de jus de lime\r\n1 c. Ã  tab (15 ml) d''assaisonnement au chili\r\n1 c. Ã  tab (15 ml) de piment chili (de type jalapeÃ±o) frais, hachÃ© finement\r\n1 c. Ã  tab (15 ml) d''huile vÃ©gÃ©tale\r\n1/2 c. Ã  thÃ© (2 ml) de sel\r\n4 filets de saumon avec la peau (environ 6 oz/175 g chacun)\r\n1 poivron rouge coupÃ© en quatre\r\n1 poivron jaune coupÃ© en quatre\r\n2 courgettes coupÃ©es en tranches de 1/2 po (1 cm) d''Ã©paisseur\r\n1 c. Ã  tab (15 ml) d''huile d''olive\r\n1 c. Ã  thÃ© (5 ml) de mÃ©lange de fines herbes sÃ©chÃ©es Ã  l''italienne\r\n1/4 c. Ã  thÃ© (1 ml) de poivre noir du moulin', 4, 20, 10, 'Four', 'MÃ©langer le jus de lime, l''assaisonnement au chili, le piment chili, l''huile vÃ©gÃ©tale et 1/4 de cuillerÃ©e Ã  thÃ© (1 ml) du sel.\r\nÃ‰tendre la prÃ©paration au piment chili sur le dessus des filets de saumon.\r\nLaisser reposer pendant 10 minutes Ã  la tempÃ©rature ambiante.\r\nEntre-temps, mettre les poivrons rouge et jaune et les courgettes dans un bol.\r\nAjouter l''huile d''olive, le mÃ©lange de fines herbes sÃ©chÃ©es, le poivre et le reste du sel et mÃ©langer pour bien enrober les lÃ©gumes.\r\nRÃ©gler le barbecue au gaz Ã  puissance moyenne-Ã©levÃ©e.\r\nMettre les lÃ©gumes et les filets de saumon, la peau dessous, sur la grille huilÃ©e du barbecue.\r\nFermer le couvercle et cuire pendant environ 10 minutes ou jusqu''Ã  ce que la chair du saumon se dÃ©fasse facilement Ã  la fourchette et que les lÃ©gumes soient tendres mais encore croquants.\r\n\r\nEn accompagnement: Triangles de pain pita grillÃ©', 8, '2013-09-26 13:21:57', 'saumon_grille_avec_legume.jpg'),
(31, 'Filets de saumon aux fines herbes', 'Un fabuleux mÃ©lange de fines herbes qui enrobe nos filets de saumons. \r\nUn mets savoureux et rapide Ã  prÃ©parer qui vous mettra l''eau Ã  la bouche.', '1 c. Ã  thÃ© (5 ml) de basilic sÃ©chÃ©;\r\n1 c. Ã  thÃ© de thym (5 ml) sÃ©chÃ©;\r\n1/2 c. Ã  thÃ© (2 ml) de sel;\r\n1/2 c. Ã  thÃ© (2 ml) de poivre noir du moulin;\r\n4 filets de saumon avec la peau (environ 1 1/2 lb/750 g en tout);\r\n2 tomates coupÃ©es en deux;\r\n2 c. Ã  thÃ© (10 ml) d''huile vÃ©gÃ©tale quartiers de citron;', 4, 10, 10, 'Pï¿½le', 'Dans un petit bol, mÃ©langer le basilic, le thym, le sel et le poivre.\r\nFrotter la moitiÃ© du mÃ©lange sur les filets de saumon.\r\nParsemer le reste du mÃ©lange sur le cÃ´tÃ© coupÃ© des tomates.\r\n\r\n2. Dans un poÃªlon, chauffer l''huile Ã  feu moyen-vif.\r\nAjouter les filets de saumon, la peau dessus, et cuire pendant environ 4 minutes.\r\nRetourner le saumon et ajouter les tomates. \r\nCuire pendant environ 6 minutes ou jusqu''Ã  ce que la chair du saumon se dÃ©fasse facilement Ã  la fourchette\r\n(retourner les tomates Ã  la mi-cuisson). Servir avec des quartiers de citron.', 7, '2013-09-26 13:26:41', 'saumon_herbes_citron.jpg'),
(32, 'BouchÃ©es de saumon caramÃ©lisÃ©', 'Les multiples saveurs combinÃ©es vous combleront de bonheur. Uniquement trois ingrÃ©dients sucrÃ©e salÃ©e et le tour est jouer! Vous avez des dÃ©licieuse bouchÃ©e caramÃ©lise.', '45 ml (3 c. Ã  soupe) de marmelade Ã  lâ€™orange (ou de tartinade Ã  lâ€™orange sans sucre ajoutÃ©);\r\n30 ml (2 c. Ã  soupe) de moutarde de Dijon;\r\n30 ml (2 c. Ã  soupe) de miel;\r\nPoivre et sel;\r\n450 g (1 lb) de saumon frais sans la peau;', 44, 10, 10, 'Four', 'PrÃ©chauffer le gril du four (Ã  broil). Placer la grille au centre du four.\r\nDans un grand bol, mÃ©langer la marmelade, la moutarde et le miel.\r\nPoivrer gÃ©nÃ©reusement et ajouter une pincÃ©e de sel.\r\nCouper le saumon en cubes de 2,5 cm (1 po) de cÃ´tÃ©s\r\nAjouter les cubes de saumon Ã  la marinade et mÃ©langer pour bien enrober.\r\nDÃ©poser le saumon sur une plaque de cuisson doublÃ©e de papier parchemin et cuire 8 Ã  10 minutes ou jusquâ€™Ã  ce que le saumon soit dorÃ© et que les extrÃ©mitÃ©s soient caramÃ©lisÃ©es.\r\nServir sur des vermicelles de riz cuits et accompagner de lÃ©gumes sautÃ©s.', 9, '2013-09-26 13:29:20', 'boucher_de_saumon_caramelisÃ©.jpg'),
(33, 'Saumon au thaÃ¯', 'Sortez vous baguette pour dÃ©guster ce repas typiquement asiatique. Une recette sucrÃ©e et Ã©picÃ©e signÃ©e VH sera vous surprendre.', 'Enduit antiadhÃ©sif PAM original;\r\n4 filets de saumon sans peau (dâ€™environ 170 g/6 oz chacun);\r\n125 ml (Â½ tasse) de sauce chili sucrÃ©e ThaÃ¯ VH;\r\n30 ml (2 c. Ã  soupe) de sauce soya VH;\r\n30 ml (2 c. Ã  soupe) de jus dâ€™orange;', 4, 0, 15, 'Four', 'PrÃ©chauffer le four Ã  200 Â°C (400 Â°F).\r\nVaporiser un plat de cuisson en verre de 2 l (20 cm/8 po) dâ€™enduit antiadhÃ©sif PAMMD. Mettre le saumon dans le plat.\r\nDans un bol, mÃ©langer la sauce chili sucrÃ©e ThaÃ¯ VHMD, la sauce soya VHMD et le jus dâ€™orange. Verser sur le saumon.\r\nCuire dans un four prÃ©chauffÃ© sur la grille du centre pendant 10 Ã  15 minutes ou jusquâ€™Ã  ce que la chair du saumon se dÃ©tache facilement Ã  la fourchette.', 9, '2013-09-26 13:35:53', 'saumon_au_thai_sur_riz.jpg'),
(34, 'Doigts de saumon panner', 'Un a cÃ´tÃ© de pure dÃ©lice qui a un goÃ»t Ã  n''en laisser rÃªver. Cette recette croustillantes est sure\r\nde faire fureur Ã  un souper de groupe.', '1,5 L (6 tasses) de cÃ©rÃ©ales de flocons de maÃ¯s de type Corn Flakes, Ã©crasÃ©es; \r\n10 ml (2 c. Ã  thÃ©) de paprika ;\r\n5 ml (1 c. Ã  thÃ©) de chacun : coriandre moulue et moutarde en poudre ;\r\n450 g (1 lb) de filet de saumon sans peau coupÃ© en petites laniÃ¨res dâ€™environ 6 cm x 2 cm ;\r\n125 ml (1/2 tasse) de farine ;\r\n3 oeufs battus ;', 4, 35, 15, 'Four', 'Dans un bol, mÃ©langer les cÃ©rÃ©ales et les Ã©pices.\r\nTremper les laniÃ¨res de saumon dans la farine, les oeufs puis dans la chapelure de cÃ©rÃ©ales. RÃ©server.\r\nDÃ©poser les doigts de saumon sur la moitiÃ© de la plaque libre, Ã  cÃ´tÃ© des lÃ©gumes.\r\nPoursuivre la cuisson 15 minutes de plus.', 9, '2013-09-26 13:39:05', 'doigts_de_saumon.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
