<footer>
	<div class="container">
		<div id="resaux-sociaux">
			<p>Suivez-nous:</p>
			<img src="assets/img/ico/icon_facebook.png" alt="" />
			<img src="assets/img/ico/icon_gplus.png" alt="" />
			<img src="assets/img/ico/icon_twitter.png" alt="" />
		</div>

		<div id="footer-droite">
			<ul>
				<li><a href="#">FAQ</a></li>
				<li><a href="#">Plan du site</a></li>
				<li><a href="#">Contactez-nous</a></li>
			</ul>

			<p>Copyright &copy; 2013 Étudiants ISI-Montréal</p>
		</div>
	</div>
</footer>