<footer>
	<div class="container">
		<div id="resaux-sociaux">
			<p>Suivez-nous:</p>
			<i class="icon-facebook"></i>
			<i class="icon-twitter"></i>
			<i class="icon-gplus"></i>
			<i class="icon-linkedin"></i>
		</div>

		<div id="footer-droite">
			<ul>
				<li><a href="#">FAQ</a></li>
				<li><a href="#">Plan du site</a></li>
				<li><a href="#">Contactez-nous</a></li>
			</ul>

			<p>Copyright &copy; 2013 Étudiants ISI-Montréal</p>
		</div>
	</div>
</footer>