<header>
	<div class="container">
		<img src="assets/img/logo.png" alt="logo" />
		<span>Recettes et informations</span>


		<ul>
			<li><a href="index.php">Accueil</a></li>
			<li><a href="?page=recettes_saumon">Recettes</a></li>
			<li><a href="?page=blog">Blog</a></li>
			<li><a href="?page=apropos">À propos</a></li>
			<li><a href="?page=contact_poisson">Contact</a></li>
		</ul>
	</div>
</header>