<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40493546-3', 'isaumon.com');
  ga('send', 'pageview');

</script>

<header>
	<div class="container">
		<img src="assets/img/logo.png" alt="logo" />
		<span>Recettes et informations</span>


		<ul>
			<li><a href="index.php">Accueil</a></li>
			<li><a href="?page=recettes_saumon">Recettes</a></li>
			<li><a href="?page=blog">Blog</a></li>
			<li><a href="?page=apropos">À propos</a></li>
			<li><a href="?page=contact_poisson">Contact</a></li>
		</ul>
	</div>
</header>